apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-kjs-deployment
  namespace: kjs
  labels:
    app: portfolio-kjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-kjs
  template:
    metadata:
      labels:
        app: portfolio-kjs
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      
      volumes:
        - name: portfolio-kjs-data-volume
          persistentVolumeClaim:
            claimName: portfolio-kjs-data-pvc
        - name: portfolio-kjs-image-volume
          persistentVolumeClaim:
            claimName: portfolio-kjs-image-pvc
        - name: portfolio-kjs-profile-volume
          persistentVolumeClaim:
            claimName: portfolio-kjs-profile-pvc
        - name: portfolio-kjs-video-volume
          persistentVolumeClaim:
            claimName: portfolio-kjs-video-pvc
      
      initContainers:
      - name: init-portfolio-kjs-data
        image: busybox
        command:
        - sh
        - -c
        - |
          if [ ! -f /data/sections.json ]; then
            cat > /data/sections.json <<'EOF'
          [
            {
              "id": "section-1764264077735",
              "name": "#뮤직비디오",
              "status": "closed",
              "items": []
            }
          ]
          EOF
          fi
        volumeMounts:
        - name: portfolio-kjs-data-volume
          mountPath: /data  # PVC를 임시로 여기에 마운트
      
      containers:
      - name: portfolio-kjs-container
        image: ghcr.io/portfolio-pages/portfolio-kjs:85f330dac9dc1c617ba0b07c988989d04f0b14e3
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: portfolio-kjs-data-volume
          mountPath: /app/data
        - name: portfolio-kjs-image-volume
          mountPath: /app/public/images
        - name: portfolio-kjs-profile-volume
          mountPath: /app/public/profile
        - name: portfolio-kjs-video-volume
          mountPath: /app/public/videos
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10