apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-kjs-ingress
  namespace: kjs
  annotations:
    # kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: asdf.portfolio-kjs.kro.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-kjs-service
            port:
              number: 80