apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - persistentvolumeclaim.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: portfolio-video

images:
  - name: portfolio-video
    newName: <registry>/portfolio-video
    newTag: latest

